name: Build and Deploy

on:
  push:
    branches: [ master ]
    
  #Run Workflow manually
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install dependencies
        uses: npm ci
      - name: Build dependencies
        uses: npm run build
      - name: Archieve production artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ./build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: ./build
      - name: Deploy to firebase
        uses: w9jds/firebase-actions@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
